export interface Painting {
  id: string;
  title: string;
  category: 'Landscapes' | 'Flowers' | 'Animals' | 'Birds' | 'Misc' | 'Pencil Drawings';
  price: number;
  image: string;
  description: string;
  dimensions: string;
  available: boolean;
}

export const paintings: Painting[] = [
  {
    id: '2',
    title: "Cathy's Peony",
    category: 'Flowers',
    price: 495,
    image: '/cathys-peony.jpg',
    description: 'A stunning oil painting of peonies in full bloom, capturing their delicate petals and vibrant colors.',
    dimensions: '11" x 14"',
    available: true,
  },
  {
    id: '8',
    title: 'Victorian Summer House',
    category: 'Misc',
    price: 575,
    image: '/victorian-house.jpg',
    description: 'Charming Victorian home adorned with patriotic bunting, rendered in delicate watercolors with architectural detail.',
    dimensions: '14" x 18"',
    available: true,
  },
  {
    id: '9',
    title: 'White Blossoms',
    category: 'Flowers',
    price: 450,
    image: '/white-flowers.jpg',
    description: 'Luminous white flowers with intricate detail, showcasing delicate petals and vibrant green foliage in watercolor.',
    dimensions: '12" x 16"',
    available: true,
  },
  {
    id: '10',
    title: 'Desert Twilight',
    category: 'Landscapes',
    price: 595,
    image: '/desert-sunset.jpg',
    description: 'Majestic saguaro cacti silhouetted against a spectacular desert sunset, painted in rich oils with dramatic lighting.',
    dimensions: '18" x 24"',
    available: true,
  },
  {
    id: '11',
    title: 'Mountain Majesty',
    category: 'Landscapes',
    price: 485,
    image: '/mountain-peak.jpg',
    description: 'Dramatic mountain peak with layered geological formations, captured in soft watercolor washes and fine detail.',
    dimensions: '14" x 14"',
    available: true,
  },
  {
    id: '12',
    title: 'Tranquil Evening',
    category: 'Landscapes',
    price: 525,
    image: '/golden-sunset.jpg',
    description: 'Serene watercolor sunset with golden reflections dancing across calm waters, evoking peaceful twilight moments.',
    dimensions: '16" x 20"',
    available: true,
  },
  {
    id: '13',
    title: 'Mountain Path',
    category: 'Landscapes',
    price: 545,
    image: '/mountain-path.jpg',
    description: 'Winding path through purple heather leading to snow-capped peaks, with golden aspens catching the light.',
    dimensions: '16" x 20"',
    available: true,
  },
  {
    id: '14',
    title: 'Lupines in Bloom',
    category: 'Flowers',
    price: 465,
    image: '/lupines-autumn.jpg',
    description: 'Vibrant lupines in full bloom with autumn leaves, rich in color and botanical detail.',
    dimensions: '14" x 18"',
    available: true,
  },
  {
    id: '15',
    title: 'European Courtyard',
    category: 'Misc',
    price: 585,
    image: '/courtyard-garden.jpg',
    description: 'Enchanting European courtyard with stone archways, potted plants, and dappled sunlight creating an inviting scene.',
    dimensions: '16" x 20"',
    available: true,
  },
  {
    id: '16',
    title: 'Young Portrait',
    category: 'Misc',
    price: 650,
    image: '/young-boy-portrait.jpg',
    description: 'Tender portrait of a young child, capturing innocence and personality with masterful watercolor technique.',
    dimensions: '12" x 16"',
    available: true,
  },
  {
    id: '17',
    title: 'Sunflowers in Crystal',
    category: 'Flowers',
    price: 525,
    image: '/sunflowers-crystal-vase.jpg',
    description: 'Radiant sunflowers arranged in an elegant cut-crystal vase, capturing the play of light through glass and the warmth of golden petals.',
    dimensions: '16" x 20"',
    available: true,
  },
  {
    id: '18',
    title: 'Garden Cottage',
    category: 'Misc',
    price: 595,
    image: '/cottage-garden.jpg',
    description: 'Idyllic cottage nestled in a flourishing garden, rendered in vibrant watercolors with lush botanical detail and architectural charm.',
    dimensions: '16" x 20"',
    available: true,
  },
  {
    id: '19',
    title: 'Artichoke with Bees',
    category: 'Flowers',
    price: 495,
    image: '/artichoke-bees.jpg',
    description: 'Stunning macro detail of an artichoke flower in full bloom with bees gathering nectar, showcasing intricate purple spines and vibrant color.',
    dimensions: '16" x 20"',
    available: true,
  },
  {
    id: '20',
    title: 'Pink English Roses',
    category: 'Flowers',
    price: 485,
    image: '/pink-roses-watercolor.jpg',
    description: 'Delicate watercolor of lush pink English roses with soft petals and buds, rendered in luminous transparent layers.',
    dimensions: '14" x 18"',
    available: true,
  },
  {
    id: '21',
    title: 'Colorful Rooster',
    category: 'Birds',
    price: 545,
    image: '/colorful-rooster.jpg',
    description: 'Majestic rooster with brilliant orange, blue, and red plumage, displaying dramatic tail feathers against a dark background.',
    dimensions: '16" x 20"',
    available: true,
  },
  {
    id: '22',
    title: 'Scarlet Macaw',
    category: 'Birds',
    price: 525,
    image: '/scarlet-macaw.jpg',
    description: 'Vibrant scarlet macaw perched on driftwood, capturing the brilliant red, blue, and yellow feathers with stunning realism.',
    dimensions: '16" x 20"',
    available: true,
  },
  {
    id: '23',
    title: 'Forest Stream',
    category: 'Landscapes',
    price: 565,
    image: '/forest-stream.jpg',
    description: 'Tranquil woodland stream with crystal-clear water flowing over rocks, surrounded by birch trees and soft morning mist.',
    dimensions: '18" x 24"',
    available: true,
  },
  {
    id: '24',
    title: 'Winter Road',
    category: 'Landscapes',
    price: 545,
    image: '/winter-road.jpg',
    description: 'Snowy country road winding through bare aspen trees with a lone evergreen, capturing the quiet beauty of winter.',
    dimensions: '16" x 20"',
    available: true,
  },
  {
    id: '25',
    title: 'Autumn Road',
    category: 'Landscapes',
    price: 565,
    image: '/autumn-road.jpg',
    description: 'Winding country road through vibrant fall foliage in gold, orange, and red, with dappled sunlight filtering through the canopy.',
    dimensions: '18" x 24"',
    available: true,
  },
  {
    id: '26',
    title: 'Pink and Yellow Lilies',
    category: 'Flowers',
    price: 485,
    image: '/pink-yellow-lilies.jpg',
    description: 'Elegant lily blooms in soft pink and yellow tones with delicate stamens, rendered in watercolor with botanical precision.',
    dimensions: '14" x 18"',
    available: true,
  },
  {
    id: '27',
    title: 'Winter Stream Reflections',
    category: 'Landscapes',
    price: 595,
    image: '/winter-stream-reflections.jpg',
    description: 'Serene winter creek with a gnarled tree trunk, capturing perfect reflections in the still blue water with frost-touched branches.',
    dimensions: '18" x 24"',
    available: true,
  },
  {
    id: '28',
    title: 'Blue-Eyed Cat',
    category: 'Animals',
    price: 525,
    image: '/fluffy-cat.jpg',
    description: 'Portrait of a majestic long-haired cat with striking blue eyes, rendered in soft pastels capturing the fluffy texture and gentle expression.',
    dimensions: '16" x 20"',
    available: true,
  },
  {
    id: '29',
    title: 'Purple Coneflowers',
    category: 'Flowers',
    price: 495,
    image: '/purple-coneflowers.jpg',
    description: 'Vibrant echinacea blooms in rich purples and pinks with golden centers, painted with impressionistic brushwork against a dreamy background.',
    dimensions: '16" x 16"',
    available: true,
  },
  {
    id: '30',
    title: 'Orange Blossoms',
    category: 'Flowers',
    price: 485,
    image: '/orange-blossoms.jpg',
    description: 'Luminous watercolor of ripe oranges on the branch with delicate white blossoms, capturing the essence of a citrus grove.',
    dimensions: '14" x 18"',
    available: true,
  },
  {
    id: '31',
    title: 'Fairy on Lily',
    category: 'Misc',
    price: 595,
    image: '/fairy-on-lily.jpg',
    description: 'Enchanting fantasy scene of a winged fairy resting on a giant lily flower, painted with magical luminosity and intricate detail.',
    dimensions: '18" x 24"',
    available: true,
  },
  {
    id: '32',
    title: 'Magnolia and Butterfly',
    category: 'Flowers',
    price: 525,
    image: '/magnolia-butterfly.jpg',
    description: 'Delicate pink magnolia blossoms with a monarch butterfly, rendered in soft oils with translucent petals and dreamy atmosphere.',
    dimensions: '16" x 20"',
    available: true,
  },
  {
    id: '33',
    title: 'Red Chairs in Provence',
    category: 'Misc',
    price: 595,
    image: '/red-chairs-courtyard.jpg',
    description: 'Charming French courtyard scene with vibrant red wicker chairs, weathered stone walls, and geraniums in dappled sunlight.',
    dimensions: '18" x 24"',
    available: true,
  },
  {
    id: '34',
    title: 'Starling with Autumn Berries',
    category: 'Birds',
    price: 545,
    image: '/starling-berries.jpg',
    description: 'European starling perched among ripe autumn berries and golden leaves, showcasing iridescent plumage with stunning realism.',
    dimensions: '16" x 20"',
    available: true,
  },
  {
    id: '35',
    title: 'Purple Iris',
    category: 'Flowers',
    price: 485,
    image: '/purple-iris.jpg',
    description: 'Elegant bearded iris in rich purple and lavender tones, painted in transparent watercolor with botanical precision and grace.',
    dimensions: '14" x 18"',
    available: true,
  },
  {
    id: '36',
    title: 'Moonrise Over Mountains',
    category: 'Landscapes',
    price: 595,
    image: '/moonrise-mountains.jpg',
    description: 'Dramatic alpine landscape with layered peaks catching sunset light and a full moon rising in the blue sky above.',
    dimensions: '18" x 24"',
    available: true,
  },
  {
    id: '37',
    title: 'Mountain Bluebird with Magnolia',
    category: 'Birds',
    price: 565,
    image: '/bluebird-magnolia.jpg',
    description: 'Brilliant mountain bluebird perched among soft pink magnolia blossoms, combining wildlife and floral beauty in harmonious composition.',
    dimensions: '18" x 18"',
    available: true,
  },
  {
    id: '38',
    title: 'Yellow Roses',
    category: 'Flowers',
    price: 485,
    image: '/yellow-roses.jpg',
    description: 'Radiant yellow and orange roses in transparent watercolor, with luminous petals and rich color transitions against a cool background.',
    dimensions: '14" x 18"',
    available: true,
  },
  {
    id: '39',
    title: 'Blue Wren',
    category: 'Birds',
    price: 525,
    image: '/blue-wren.jpg',
    description: 'Charming blue wren clinging to a branch, painted with soft feather detail and gentle background wash in oils.',
    dimensions: '16" x 20"',
    available: true,
  },
  {
    id: '40',
    title: 'Alpine Panorama',
    category: 'Landscapes',
    price: 625,
    image: '/alpine-panorama.jpg',
    description: 'Breathtaking panoramic view of snow-capped alpine peaks in soft morning light, capturing the grandeur and serenity of high mountains.',
    dimensions: '24" x 12"',
    available: true,
  },
  {
    id: '41',
    title: 'Bee on Thistle',
    category: 'Flowers',
    price: 495,
    image: '/bee-thistle.jpg',
    description: 'Macro view of a fuzzy bumblebee on a vibrant purple thistle flower against a brilliant orange background, painted with bold energy.',
    dimensions: '16" x 16"',
    available: true,
  },
  {
    id: '42',
    title: 'Hummingbird with Lilacs',
    category: 'Birds',
    price: 565,
    image: '/hummingbird-lilacs.jpg',
    description: 'Jewel-toned hummingbird hovering among lush lilac blooms, capturing iridescent feathers and the delicate grace of this tiny bird.',
    dimensions: '18" x 18"',
    available: true,
  },
  {
    id: '43',
    title: 'Abstract Sunset',
    category: 'Misc',
    price: 425,
    image: '/abstract-sunset.jpg',
    description: 'Warm abstract sunset composition with layered color and atmospheric light.',
    dimensions: '3" x 12"',
    available: true,
  },
  {
    id: '44',
    title: 'Evening in Calgary',
    category: 'Landscapes',
    price: 495,
    image: '/evening-in-calgary.jpg',
    description: 'Calgary evening scene capturing soft light and urban landscape atmosphere.',
    dimensions: '10" x 10"',
    available: true,
  },
  {
    id: '45',
    title: 'Moon at Night',
    category: 'Landscapes',
    price: 465,
    image: '/moon-at-night.jpg',
    description: 'Night landscape with moonlit tones and a calm, contemplative mood.',
    dimensions: '6" x 12"',
    available: true,
  },
  {
    id: '46',
    title: 'Sunset in Cochrane',
    category: 'Landscapes',
    price: 425,
    image: '/sunset-in-cochrane.jpg',
    description: 'Cochrane sunset scene with vivid sky color and distant landscape depth.',
    dimensions: '9" x 3"',
    available: true,
  },
  {
    id: '47',
    title: 'The Gulf Islands',
    category: 'Landscapes',
    price: 485,
    image: '/the-gulf-islands.jpg',
    description: 'Landscape inspired by the Gulf Islands with coastal color and open space.',
    dimensions: '8" x 10"',
    available: true,
  },
  {
    id: '48',
    title: 'Heirloom Portrait Study',
    category: 'Pencil Drawings',
    price: 325,
    image: '/20001231_220116940_iOS.jpg',
    description: 'Commission pencil drawing in graphite, perfect as a one-of-a-kind gift. Wedding dress portraits are especially popular for wedding keepsakes.',
    dimensions: 'Various sizes (inches)',
    available: true,
  },
  {
    id: '49',
    title: 'Grace in Graphite',
    category: 'Pencil Drawings',
    price: 325,
    image: '/20120412_212415000_iOS.jpg',
    description: 'Commission pencil drawing in graphite, perfect as a one-of-a-kind gift. Wedding dress portraits are especially popular for wedding keepsakes.',
    dimensions: 'Various sizes (inches)',
    available: true,
  },
  {
    id: '50',
    title: 'Quiet Reflection',
    category: 'Pencil Drawings',
    price: 325,
    image: '/20120924_011648000_iOS.jpg',
    description: 'Commission pencil drawing in graphite, perfect as a one-of-a-kind gift. Wedding dress portraits are especially popular for wedding keepsakes.',
    dimensions: 'Various sizes (inches)',
    available: true,
  },
  {
    id: '51',
    title: 'Classic Elegance',
    category: 'Pencil Drawings',
    price: 325,
    image: '/20130917_140859000_iOS.jpg',
    description: 'Commission pencil drawing in graphite, perfect as a one-of-a-kind gift. Wedding dress portraits are especially popular for wedding keepsakes.',
    dimensions: 'Various sizes (inches)',
    available: true,
  },
  {
    id: '52',
    title: 'Timeless Keepsake I',
    category: 'Pencil Drawings',
    price: 325,
    image: '/20151012_004412000_iOS.jpg',
    description: 'Commission pencil drawing in graphite, perfect as a one-of-a-kind gift. Wedding dress portraits are especially popular for wedding keepsakes.',
    dimensions: 'Various sizes (inches)',
    available: true,
  },
  {
    id: '53',
    title: 'Timeless Keepsake II',
    category: 'Pencil Drawings',
    price: 325,
    image: '/20151218_055300670_iOS.jpg',
    description: 'Commission pencil drawing in graphite, perfect as a one-of-a-kind gift. Wedding dress portraits are especially popular for wedding keepsakes.',
    dimensions: 'Various sizes (inches)',
    available: true,
  },
  {
    id: '54',
    title: 'Soft Light Study',
    category: 'Pencil Drawings',
    price: 325,
    image: '/20160225_095336460_iOS.jpg',
    description: 'Commission pencil drawing in graphite, perfect as a one-of-a-kind gift. Wedding dress portraits are especially popular for wedding keepsakes.',
    dimensions: 'Various sizes (inches)',
    available: true,
  },
  {
    id: '55',
    title: 'Bridal Memory Sketch',
    category: 'Pencil Drawings',
    price: 325,
    image: '/20160512_064102000_iOS.jpg',
    description: 'Commission pencil drawing in graphite, perfect as a one-of-a-kind gift. Wedding dress portraits are especially popular for wedding keepsakes.',
    dimensions: 'Various sizes (inches)',
    available: true,
  },
  {
    id: '57',
    title: 'Delicate Details',
    category: 'Pencil Drawings',
    price: 325,
    image: '/20160710_080412000_iOS.jpg',
    description: 'Commission pencil drawing in graphite, perfect as a one-of-a-kind gift. Wedding dress portraits are especially popular for wedding keepsakes.',
    dimensions: 'Various sizes (inches)',
    available: true,
  },
  {
    id: '58',
    title: 'Sunlit Meadow',
    category: 'Landscapes',
    price: 495,
    image: '/20160719_071957000_iOS.jpg',
    description: 'Original color painting from Paula collection.',
    dimensions: 'Various sizes (inches)',
    available: true,
  },
  {
    id: '59',
    title: 'Wedding Dress Keepsake I',
    category: 'Pencil Drawings',
    price: 325,
    image: '/20170313_072248000_iOS.jpg',
    description: 'Commission pencil drawing in graphite, perfect as a one-of-a-kind gift. Wedding dress portraits are especially popular for wedding keepsakes.',
    dimensions: 'Various sizes (inches)',
    available: true,
  },
  {
    id: '60',
    title: 'Wedding Dress Keepsake II',
    category: 'Pencil Drawings',
    price: 325,
    image: '/20170606_101444580_iOS.jpg',
    description: 'Commission pencil drawing in graphite, perfect as a one-of-a-kind gift. Wedding dress portraits are especially popular for wedding keepsakes.',
    dimensions: 'Various sizes (inches)',
    available: true,
  },
  {
    id: '61',
    title: 'Vintage Lace Study',
    category: 'Pencil Drawings',
    price: 325,
    image: '/20170727_130442000_iOS.jpg',
    description: 'Commission pencil drawing in graphite, perfect as a one-of-a-kind gift. Wedding dress portraits are especially popular for wedding keepsakes.',
    dimensions: 'Various sizes (inches)',
    available: true,
  },
  {
    id: '62',
    title: 'Silk and Satin Study',
    category: 'Pencil Drawings',
    price: 325,
    image: '/20170727_132026000_iOS.jpg',
    description: 'Commission pencil drawing in graphite, perfect as a one-of-a-kind gift. Wedding dress portraits are especially popular for wedding keepsakes.',
    dimensions: 'Various sizes (inches)',
    available: true,
  },
  {
    id: '63',
    title: 'Golden Prairie Evening',
    category: 'Landscapes',
    price: 495,
    image: '/20170902_061754000_iOS.jpg',
    description: 'Original color painting from Paula collection.',
    dimensions: 'Various sizes (inches)',
    available: true,
  },
  {
    id: '64',
    title: 'Autumn Canopy',
    category: 'Landscapes',
    price: 495,
    image: '/20171025_063755000_iOS.jpg',
    description: 'Original color painting from Paula collection.',
    dimensions: 'Various sizes (inches)',
    available: true,
  },
  {
    id: '65',
    title: 'Poised in Pencil',
    category: 'Pencil Drawings',
    price: 325,
    image: '/20171113_104848560_iOS.jpg',
    description: 'Commission pencil drawing in graphite, perfect as a one-of-a-kind gift. Wedding dress portraits are especially popular for wedding keepsakes.',
    dimensions: 'Various sizes (inches)',
    available: true,
  },
  {
    id: '66',
    title: 'Spring Bouquet Study',
    category: 'Flowers',
    price: 495,
    image: '/20180419_020820000_iOS.jpg',
    description: 'Original color painting from Paula collection.',
    dimensions: 'Various sizes (inches)',
    available: true,
  },
  {
    id: '67',
    title: 'Garden Blooms in Light',
    category: 'Flowers',
    price: 495,
    image: '/20180422_101211000_iOS.jpg',
    description: 'Original color painting from Paula collection.',
    dimensions: 'Various sizes (inches)',
    available: true,
  },
  {
    id: '68',
    title: 'Graceful Lines',
    category: 'Pencil Drawings',
    price: 325,
    image: '/20180503_051356000_iOS.jpg',
    description: 'Commission pencil drawing in graphite, perfect as a one-of-a-kind gift. Wedding dress portraits are especially popular for wedding keepsakes.',
    dimensions: 'Various sizes (inches)',
    available: true,
  },
  {
    id: '69',
    title: 'Heirloom Gown Portrait',
    category: 'Pencil Drawings',
    price: 325,
    image: '/20180924_075554000_iOS.jpg',
    description: 'Commission pencil drawing in graphite, perfect as a one-of-a-kind gift. Wedding dress portraits are especially popular for wedding keepsakes.',
    dimensions: 'Various sizes (inches)',
    available: true,
  },
  {
    id: '70',
    title: 'Berry Branch Songbird',
    category: 'Birds',
    price: 495,
    image: '/20181126_051506630_iOS.jpg',
    description: 'Original color painting from Paula collection.',
    dimensions: 'Various sizes (inches)',
    available: true,
  },
  {
    id: '71',
    title: 'Family Treasure Sketch',
    category: 'Pencil Drawings',
    price: 325,
    image: '/20190207_103636000_iOS.jpg',
    description: 'Commission pencil drawing in graphite, perfect as a one-of-a-kind gift. Wedding dress portraits are especially popular for wedding keepsakes.',
    dimensions: 'Various sizes (inches)',
    available: true,
  },
  {
    id: '72',
    title: 'Summer Orchard Glow',
    category: 'Landscapes',
    price: 495,
    image: '/20190813_201148722_iOS.jpg',
    description: 'Original color painting from Paula collection.',
    dimensions: 'Various sizes (inches)',
    available: true,
  },
  {
    id: '73',
    title: 'Monochrome Elegance',
    category: 'Pencil Drawings',
    price: 325,
    image: '/20191026_080358280_iOS.jpg',
    description: 'Commission pencil drawing in graphite, perfect as a one-of-a-kind gift. Wedding dress portraits are especially popular for wedding keepsakes.',
    dimensions: 'Various sizes (inches)',
    available: true,
  },
  {
    id: '74',
    title: 'Coastal Sky Reflections',
    category: 'Landscapes',
    price: 495,
    image: '/20200919_160525336_iOS.jpg',
    description: 'Original color painting from Paula collection.',
    dimensions: 'Various sizes (inches)',
    available: true,
  },
  {
    id: '75',
    title: 'Wildflower Harmony',
    category: 'Flowers',
    price: 495,
    image: '/20210418_150038171_iOS.jpg',
    description: 'Original color painting from Paula collection.',
    dimensions: 'Various sizes (inches)',
    available: true,
  },
  {
    id: '76',
    title: 'Keepsake Commission Study',
    category: 'Pencil Drawings',
    price: 325,
    image: '/20211102_213839438_iOS.jpg',
    description: 'Commission pencil drawing in graphite, perfect as a one-of-a-kind gift. Wedding dress portraits are especially popular for wedding keepsakes.',
    dimensions: 'Various sizes (inches)',
    available: true,
  },
  {
    id: '77',
    title: 'Evening Garden Path',
    category: 'Landscapes',
    price: 495,
    image: '/20220219_174739307_iOS.jpg',
    description: 'Original color painting from Paula collection.',
    dimensions: 'Various sizes (inches)',
    available: true,
  },
  {
    id: '78',
    title: 'Songbird and Blossom',
    category: 'Birds',
    price: 495,
    image: '/20220304_233601479_iOS.jpg',
    description: 'Original color painting from Paula collection.',
    dimensions: 'Various sizes (inches)',
    available: true,
  },
  {
    id: '79',
    title: 'Wedding Dress Keepsake III',
    category: 'Pencil Drawings',
    price: 325,
    image: '/20220924_175205917_iOS.jpg',
    description: 'Commission pencil drawing in graphite, perfect as a one-of-a-kind gift. Wedding dress portraits are especially popular for wedding keepsakes.',
    dimensions: 'Various sizes (inches)',
    available: true,
  },
  {
    id: '80',
    title: 'Desert Bloom',
    category: 'Flowers',
    price: 495,
    image: '/20221027_235045748_iOS.jpg',
    description: 'Original color painting from Paula collection.',
    dimensions: 'Various sizes (inches)',
    available: true,
  },
  {
    id: '81',
    title: 'Cherished Moments',
    category: 'Pencil Drawings',
    price: 325,
    image: '/20240109_205859014_iOS.jpg',
    description: 'Commission pencil drawing in graphite, perfect as a one-of-a-kind gift. Wedding dress portraits are especially popular for wedding keepsakes.',
    dimensions: 'Various sizes (inches)',
    available: true,
  },
  {
    id: '82',
    title: 'Mountain Morning Light',
    category: 'Landscapes',
    price: 495,
    image: '/20240823_171938072_iOS.jpg',
    description: 'Original color painting from Paula collection.',
    dimensions: 'Various sizes (inches)',
    available: true,
  },
  {
    id: '83',
    title: 'Sentimental Sketch',
    category: 'Pencil Drawings',
    price: 325,
    image: '/20240927_204448166_iOS.jpg',
    description: 'Commission pencil drawing in graphite, perfect as a one-of-a-kind gift. Wedding dress portraits are especially popular for wedding keepsakes.',
    dimensions: 'Various sizes (inches)',
    available: true,
  },
  {
    id: '84',
    title: 'Lilac Breeze',
    category: 'Flowers',
    price: 495,
    image: '/20250325_005559057_iOS.jpg',
    description: 'Original color painting from Paula collection.',
    dimensions: 'Various sizes (inches)',
    available: true,
  },
  {
    id: '85',
    title: 'Sunset Ridge',
    category: 'Landscapes',
    price: 495,
    image: '/20250326_231938378_iOS.jpg',
    description: 'Original color painting from Paula collection.',
    dimensions: 'Various sizes (inches)',
    available: true,
  },
  {
    id: '86',
    title: 'Riverbank in Spring',
    category: 'Landscapes',
    price: 495,
    image: '/20250327_221854597_iOS.jpg',
    description: 'Original color painting from Paula collection.',
    dimensions: 'Various sizes (inches)',
    available: true,
  },
  {
    id: '87',
    title: 'Rose Study in Pink',
    category: 'Flowers',
    price: 495,
    image: '/20250421_152218488_iOS.jpg',
    description: 'Original color painting from Paula collection.',
    dimensions: 'Various sizes (inches)',
    available: true,
  },
  {
    id: '88',
    title: 'Aspen Gold',
    category: 'Landscapes',
    price: 495,
    image: '/20250823_161937261_iOS.jpg',
    description: 'Original color painting from Paula collection.',
    dimensions: 'Various sizes (inches)',
    available: true,
  },
  {
    id: '89',
    title: 'Twilight Horizon',
    category: 'Landscapes',
    price: 495,
    image: '/20251003_223358894_iOS.jpg',
    description: 'Original color painting from Paula collection.',
    dimensions: 'Various sizes (inches)',
    available: true,
  },
  {
    id: '90',
    title: 'Forever Dress Portrait',
    category: 'Pencil Drawings',
    price: 325,
    image: '/20251117_175549842_iOS.jpg',
    description: 'Commission pencil drawing in graphite, perfect as a one-of-a-kind gift. Wedding dress portraits are especially popular for wedding keepsakes.',
    dimensions: 'Various sizes (inches)',
    available: true,
  },
  {
    id: '91',
    title: 'Still Life in Warm Light',
    category: 'Misc',
    price: 495,
    image: '/20251128_185602528_iOS.jpg',
    description: 'Original color painting from Paula collection.',
    dimensions: 'Various sizes (inches)',
    available: true,
  },
  {
    id: '92',
    title: 'Bespoke Bridal Study',
    category: 'Pencil Drawings',
    price: 325,
    image: '/20260213_235738061_iOS.jpg',
    description: 'Commission pencil drawing in graphite, perfect as a one-of-a-kind gift. Wedding dress portraits are especially popular for wedding keepsakes.',
    dimensions: 'Various sizes (inches)',
    available: true,
  },
];
